### PR TITLE
Enable to add Headers via Map

### PR DESCRIPTION
**Pull request by wofr**
Add headers via map

### CODE REVIEW

**Comment by elithrar** [comment]
Can you explain the rationale behind this?

**Comment by wofr** [comment]
Well I found it more "natural" adding headers from a map (key,value) rather than from a list of strings.  In my setup I got the headers I 've to use handed-over via a map and I don't not want to convert the header-map into a header-array which is than again converteded into a map.   It just about the usability.

**Comment by elithrar** [comment]
HTTP headers are typically `http.Header` - which is a `map[string][]string`, not a `map[string]string`.

If you have an existing data structure, write a helper to convert. I'm not sure this adds value for all (or even most) users of this library.

**Comment by wofr** [comment]
Fair enough!
Personally I find it handier handling my headers with a map rather than array of string.  This prevents me form accidently overriding header values, but of course implementing a converter works as well.

**Pull request closed without merging**
