### PR TITLE
[ISSUE-287] GetQueriesTemplates and GetQueriesRegexp extraction

### PR DESCRIPTION
**Pull request by paulbes**
Developers can now extract the query templates and regexps from a router as lists of combined query pairs.

## Description
The implementation returns lists of combined pairs of registered `Queries`; as templates or regexps. It was deemed more appropriate to return lists, at least for regexps, rather than a joined string of all combined pairs, since each query pair is considered a separate matcher, e.g., if we have the following: `Queries("foo", "{v1}", "baz", "{v2}")`, when joined using regexps we would end up with: `^foo=(?P<v0>.*)$,^baz=(?P<v0>.*)$`. The multiple `v0` entries might be confusing. For the query template, we could consider joining, but even then it will be a bit strange, e.g., `foo={v1},baz={v2}`.

## Motivation and Context
Being able to extract all parts of a registered route, including queries, can be very useful. In particular when generating REST API documentation. In addition, it can be useful to determine that tests have been written for all registered routes; by matching recorded and registered routes with their various parts.

## How Has This Been Tested (if appropriate)? 
Added `testQueriesRegexp` and `testQueriesTemplates` methods and added `queriesTemplate` and `queriesRegexp` fields to `routeTest`. All `TestQueries` cases are using this functionality.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring (non-breaking changes, no bug fixing, no new features)
- [x] Testing (New unit/integration/performance tests)

## Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Related tickets or issues:
This resolves issue #287

### CODE REVIEW

**Comment by elithrar** [comment]
Thanks for the detailed write-up: it helps a lot. The patch looks good to
me; @kisielk as a second pair of eyes before merging.

**Comment by kisielk** [comment]
Is there a reason you'd want just the Regexp or just the templates? Is there value in it being two separate functions?

**Comment by paulbes** [comment]
I can't speak for all use-cases, but we will end up using `GetQueriesTemplates` primarily, I added the `GetQueriesRegexp` for completeness primarily; there being an equivalent one for `Path`. I am not sure when it would be used, perhaps in use-cases where a developer wants to examine the final regexp that is being matched with by mux.

Are you considering merging them into one or dropping either? If merging, what would this look like?

**Comment by paulbes** [comment]
Do we need to make any changes to this PR or should it be merged?

**Comment by elithrar** [comment]
If @kisielk is OK with the API here then it’s OK to merge.

**Comment by kisielk** [comment]
The symmetry with the `GetPathXXX` methods makes sense. Sorry I missed the last email update. Thanks for the patch!

**Pull request merged**
