### PR TITLE
Store vars and route in context.Context when go1.7+ is used

### PR DESCRIPTION
**Pull request by ejholmes**
Fixes https://github.com/gorilla/mux/issues/168

This should be backwards compatible, since the usage of gorilla/context was an implementation detail and not exposed publicly.

When go1.7+ is used, the native [context.Context](https://tip.golang.org/pkg/net/http/#Request.Context) object on the http.Request will be used. On older version of go, gorilla/context will be used.

### CODE REVIEW

**Comment by elithrar** [comment]
This LGTM! If @kisielk is happy with the PR as well we can merge.

**Comment by kisielk** [comment]
I was actually thinking of doing that this weekend, but I guess you beat me to it ! 

The implementation looks great to me, very elegant.

The only thing I can think of it breaking is people who were manually extracting route vars via the gorilla/context package, but nobody should be doing that...

**Comment by elithrar** [comment]
@kisielk Thankfully we didn't expose the context keys in #167 or #112!

Thanks for merging as well.

**Comment by kisielk** [comment]
Yeah, that was explicitly for this reason, so we could change the context
storage method in the future.

**Comment by jingweno** [comment]
:+1: Was thinking of doing this.

**Pull request merged**
