### PR TITLE
pattern aliases

### PR DESCRIPTION
**Pull request by HiveTraum**
This feature introduces ability to register aliases for some often used regular expressions. 

For example path as this:
`/{category:[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}}/{product:[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}}`
can be transformed into this
`/{category:uuid}/{product:uuid}`

You need just use register it
```
router := NewRouter()
router.RegisterPattern("uuid", "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}")
router.Path("/{category:uuid}")
router.Path("/{product:uuid}")
router.Path("/{order:uuid}")
router.Path("/{user:uuid}")
```

1. New method `RegisterPattern` on `Route` struct
2. New method `RegisterPattern` on `Router` struct

### CODE REVIEW

**Comment by elithrar** [comment]
I like the idea - although you should check beforehand to save wasted effort 😉

Can you also:

1. add a new section to the README with your usage example - I.e under a "Re-using Regular Expressions"
2. add a `ExampleRegisterPattern` that demonstrates how to use it as well?

mux has a lot of features and it helps to document new ones well.

**Comment by HiveTraum** [comment]
> I like the idea - although you should check beforehand to save wasted effort 😉
> 
> Can you also:
> 
> 1. add a new section to the README with your usage example - I.e under a "Re-using Regular Expressions"
> 2. add a `ExampleRegisterPattern` that demonstrates how to use it as well?
> 
> mux has a lot of features and it helps to document new ones well.

done👍

**Comment by HiveTraum** [comment]
@elithrar , are there any other changes needed?

**Comment by tharoldD** [comment]
it would be nice to get this in

**Comment by HiveTraum** [comment]
Can anyone take a look? I noticed that the project came to life

**Comment by amustaque97** [comment]
> Can anyone take a look? I noticed that the project came to life

I will be reviewing this PR in sometime. If I missed it due to any reason. Request you to ping me.

**Pull request closed without merging**
