### PR TITLE
Update ancestors parameter for WalkFunc for matcher subrouters

### LINKED ISSUE #263: Walk does not set ancestors properly for subroutes
The `ancestors` parameter of `WalkFunc` is currently only populated for handler subrouters (and not for matcher subrouters).

Test:

```go
func TestWalkAncestors(t *testing.T) {
	router := mux.NewRouter()
	g := router.Path("/g").Subrouter()
	g.PathPrefix("/o").Subrouter()

	router.Walk(func(route *mux.Route, router *mux.Router, ancestors []*mux.Route) error {
		tmpl, _ := route.GetPathTemplate()
		fmt.Printf("route: %s, ancestors: %v\n", tmpl, ancestors)
		return nil
	})
}
```

Current output:

```
route: /g, ancestors: []
route: /g/o, ancestors: []
```

Expected output:

```
route: /g, ancestors: []
route: /g/o, ancestors: [0xc420131ea0]
```

### PR DESCRIPTION
**Pull request by nmiyake**
Fixes #263

### CODE REVIEW

**Comment by nmiyake** [comment]
@elithrar @kisielk I believe this fix is fairly straightforward -- would appreciate feedback/review when you get a chance!

**Comment by elithrar** [comment]
Can you also add a (short) example of using WalkFunc to the README to supplement this? Add it as the next section after https://github.com/gorilla/mux#registered-urls

**Comment by nmiyake** [comment]
The ["Listing Routes"](https://github.com/gorilla/mux#listing-routes) section of the README contains an example of using `WalkFunc` -- do you want me to add another section separately from that, add something (or rename) that section, or is it okay as-is given that the section exists?

**Comment by nmiyake** [comment]
Addressed PR feedback: tightened up the example in "Listing Routes" a bit, renamed it to "Walking Routes" and moved it to a section after "Registered URLs".

Ready for review.

**Comment by nmiyake** [comment]
@elithrar @kisielk thanks for merging #265 -- if you could review/provide feedback on this PR and move to merge as well that would be great (both of them together will allow me to resolve the underlying issue described in #258)

**Pull request merged**
