### PR TITLE
Adding in a check for routes with just /

### PR DESCRIPTION
**Pull request by ShaneSaww**
This should fix https://github.com/gorilla/mux/issues/79. 
Looking for feedback!

### CODE REVIEW

**Comment by elithrar** [comment]
Thanks for submitting this. Will review tomorrow!

**Comment by ShaneSaww** [comment]
If it helps this is the code I used to test:
```go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/gorilla/mux"
)

func main() {
	router := mux.NewRouter()
	adminRouter := router.PathPrefix("/admin").Subrouter()
	adminRouter.HandleFunc("", someHandler)
	adminRouter.HandleFunc("/", someHandler)

	log.Print("Listening on :5000")
	httpErr := http.ListenAndServe(":5000", router)
	if httpErr != nil {
		log.Fatal("ListenAndServe:", httpErr)
	}
}

func someHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Printf("In the handler\n")
}

```

Running this should allow you to hit both 
 localhost:5000/admin
 localhost:5000/admin/

**Comment by elithrar** [comment]
Can you add some additional test cases to this?

1. `/foo/bar`
2. `/foo/bar/`
3. `/foo` with a Queries() matcher

This will help prevent any regressions in future. mux has grown a lot over time & I want to make sure the testing story is as robust as it can be.

**Comment by ShaneSaww** [comment]
@elithrar  Just added the extra test cases!

**Comment by elithrar** [comment]
LGTM - @kisielk?

**Comment by kisielk** [comment]
LGTM as well. Thanks!

**Comment by scisci** [comment]
The code added doesn't seem to make any sense:

`if tpl == "/" && (len(tpl) == 0 || tpl[0] != '/') {`

Wouldn't that always evaluate to false?

**Comment by ShaneSaww** [comment]
@scisci the reason that it makes sense (and it's kinda strange) is that if    

`tpl = "/"` then  `tpl[0] == 47`

 which is why  `if tpl == "/" && (len(tpl) == 0 || tpl[0] != '/') {` works. 

With all that in mind you are correct that `if len(tpl) > 0 && tpl[0] != '/' {` would make more sense.

**Comment by scisci** [comment]
OK, guess I'm missing something :) 

It looked to me like this code would always return false, so it wouldn't catch truly bad templates that don't start with a slash like router.HandleFunc("someNonEmptyRouteWithNoSlash", ...)

But I'm new to gorilla so maybe this is on purpose or maybe I'm wrong.

**Comment by kisielk** [comment]
I think I agree with @scisci ... looking at it again I can't seem to make this logic make sense in my head, unless I am missing something.

**Comment by ShaneSaww** [comment]
After playing with it in the playground it seems broken. 
https://play.golang.org/p/0-N07DgH6W
I can push up a fix for it later today.

**Pull request merged**
