### PR TITLE
Feature route metadata

### LINKED ISSUE #750: [FEATURE] Route metadata
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe.

Currently it is difficult to do authorization on routes based on claim requirements, unless we do the check inside the http handler.
Coming from a C# .NET world, there it is easy because it support attributes like an [Authorize] attribute.

As workaround i added a unique name to each route, and created a authorization mapping between the route name and the authorization policy.

**Middleware**
```
var routePolicies map[string]string
var authPolicies map[string]authorization.Policy

func authMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		route := mux.CurrentRoute(r)
		policyName, ok := routePolicies[route.GetName()]
		if !ok {
			http.Error(w, "Forbidden", http.StatusForbidden)
			return
		}

		policy, ok := authPolicies[policyName]
		if !ok || !policy.MeetsRequirements(r.Context()) {
			http.Error(w, "Forbidden", http.StatusForbidden)
			return
		}

		next.ServeHTTP(w, r)
	})
}

```

**Setup**
```
// Register the route
r.HandleFunc("/v1/product", api.GetProductsHandlerV1).Methods(http.MethodGet).Name("product_api:GetProductsHandlerV1")
r.HandleFunc("/v1/product/{id}", api.GetProductByIdHandlerV1).Methods(http.MethodGet).Name("product_api:GetProductByIdHandlerV1")

// Set the route policies
routePolicies["product_api:GetProductsHandlerV1"] = "product.read"
routePolicies["product_api:GetProductByIdHandlerV1"] = "product.read"

// Create the policies
authPolicies["product.read"] = authorization.NewPolicy(
    "product.read",
    NewUserRequirement(),
    NewScopeRequirement("product.read"),
)
```

### Describe the solution that you would like.

To make it easy to create an authorization middleware with limited code, it would be nice to have metadata on a route.

Example:
```
r.HandleFunc("/v1/product", api.GetProductsHandlerV1).Methods(http.MethodGet).Metadata("authPolicy", "product.read")
r.HandleFunc("/v1/product/{id}", api.GetProductByIdHandlerV1).Methods(http.MethodGet).Metadata("authPolicy", "product.read")

func authMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		route := mux.CurrentRoute(r)
		policy, ok := authPolicies[route.GetMetadata()["authPolicy"]]
		if !ok || !policy.MeetsRequirements(r.Context()) {
			http.Error(w, "Forbidden", http.StatusForbidden)
			return
		}

		next.ServeHTTP(w, r)
	})
}
```

Route metadata could be used for many other solutions, where u want to set some properties on a route to use inside the handler or middlewares

### Describe alternatives you have considered.

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cornejong**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Go Version Update
- [ ] Dependency Update

## Description
Added metadata to route. as proposed in #750 
Documentation will be added uppon request.

## Related Tickets & Documents

- Related Issue #750 
- Closes #750 

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Run verifications and test

- [x] `make verify` is passing
- [x] `make test` is passing

### CODE REVIEW

**Comment by cornejong** [comment]
This pull request introduces metadata to route struct. The proposed changes allow attaching arbitrary metadata to routes, enabling more flexible and readable codebases. 

Here's an example of how this feature can be used:
```go
router.HandleFunc("/v1/product", handlerFunc).Metadata("authPolicy", "product.read")
// or an RBAC example
router.HandleFunc("/v1/product", handlerFunc).Metadata("allowedRoles", []Role{RoleAdmin, RoleManager, RoleEditor})

router.Use((next http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        route := mux.CurrentRoute(r)
        
        if !route.MetadataContains("authPolicy") {
            next.ServeHTTP(w, r)
            return
        }

        authPolicy, err := route.GetMetadataValue("authPolicy")
        // or define a fallback value
        authPolicy := route.GetMetadataValueOr("authPolicy", "fallback_policy")
        
        // Enforce policy ...
    })
})
```

While authorization is a common use case, the .Metadata method opens up possibilities for various other configurations, such as caching, rate limiting or any other middleware for that matter. This addition aims to enhance the modularity and maintainability of applications by leveraging route metadata for various middleware configurations. The goal is to create clean and readable codebases where functionality can be abstracted into generalized middleware, keeping handlers clean and simple.

**Review by AlexVulaj — APPROVED** [review]

**Comment by AlexVulaj** [comment]
This change makes a lot of sense to me, thanks for the contribution!

**Comment by AlexVulaj** [comment]
Sorry for the "closed" notification - that was a misclick. PR is merged now!

**Comment by cornejong** [comment]
No problemo, Thanks for the merge! Always happy to contribute.

**Pull request merged**
