### PR TITLE
Clear any match error or handler when iterating a router

### PR DESCRIPTION
**Pull request by lavoiesl**
Fixes https://github.com/gorilla/mux/issues/411

Added tests that showed the previous failing behaviour.

### CODE REVIEW

**Comment by kisielk** [comment]
Doesn't this result in just eating any errors that come from earlier routes? What if the first route checked is the right path, but has a method mismatch, and the second route is the wrong path? The method mismatch logic won't be triggered in that case.

**Comment by lavoiesl** [comment]
Very good point. It’s confusing because the `ErrMethodMismatch` logic is inverted.
I added an exception and a test for it.

It would probably be cleaner to move the allowed methods to a dedicated property, but this seems good enough for now.

**Comment by elithrar** [comment]
We should move them to a dedicated property: it will make it easier to
maintain in the future.

**Comment by lavoiesl** [comment]
As I said, I couldn't find a proper solution with a dedicated property that was working. It might take a more significant refactoring.

I had a very real bug related to this that took me a shameful amount of time to diagnose. I propose merging this as is, considering it works for the new test case without introducing a known regression, and revisit later.

**Comment by kisielk** [comment]
I am more concerned about the unknown regressions, I don't believe the test suite is fully comprehensive. 

What happens if the MatchErr is `ErrNotFound` in the first case, but then that gets wiped out to try other routes, will the `NotFoundHandler` ultimately be called?

**Comment by elithrar** [comment]
Closing in favor of #418

**Pull request closed without merging**
