### PR TITLE
Add HeadersRegexp to Router

### PR DESCRIPTION
**Pull request by chriskolenko**
Just like Headers() on the router but with Regex

### CODE REVIEW

**Comment by kisielk** [comment]
Makes sense for API consistency purposes. Can you add some tests?

**Comment by elithrar** [comment]
@chriskolenko - are you still interested in finishing this one off?

**Comment by chriskolenko** [comment]
@elithrar apologies. I'll get onto this tonight.

**Comment by elithrar** [comment]
Timed out.

**Pull request closed without merging**
