### PR TITLE
Fix minor mistake in HeadersRegexp doc

### LINKED ISSUE #666: [bug] Documentation for func (*Route) HeadersRegexp is incorrect
**Describe the bug**

The documentation example for [`func (*Route) HeadersRegexp`](https://pkg.go.dev/github.com/gorilla/mux?utm_source=godoc#Route.HeadersRegexp) is incorrect:

```go
r := mux.NewRouter()
r.HeadersRegexp("Content-Type", "application/(text|json)",
          "X-Requested-With", "XMLHttpRequest")
```

`mux.NewRouter()` returns `*mux.Router` but `HeadersRegexp` is defined on `*Route`. This is a small mistake and is not a major issue because the next (more verbose) example clarifies the mistake.

However, it's a mistake.

Should be something like:

```go
r := mux.NewRouter().NewRoute()
r.HeadersRegexp("Content-Type", "application/(text|json)",
          "X-Requested-With", "XMLHttpRequest")
```

**Versions**
> Go version: `go version`
go version go1.16.4 darwin/amd64

> package version: run `git rev-parse HEAD` inside the repo
91708ff8e35bafc8612f690a25f5dd0be6f16864

**Steps to Reproduce**
> How can the bug be triggered?

"Bug" is in documentation; triggered by looking at it.

**Expected behavior**
> What output or behaviour were you expecting instead?

As mentioned above, the example should look like:

```go
r := mux.NewRouter().NewRoute()
r.HeadersRegexp("Content-Type", "application/(text|json)",
          "X-Requested-With", "XMLHttpRequest")
```

### PR DESCRIPTION
**Pull request by Algebra8**
Fixes #666

**Summary of Changes**

1. Fixed mistake in [`HeadersRegexp`](https://github.com/gorilla/mux/blob/master/route.go#L258) docs.

> PS: Make sure your PR includes/updates tests! If you need help with this part, just ask!

Since this is a doc change I don't think it needs tests.

### CODE REVIEW

**Comment by andrew-werdna** [comment]
Since `Router` and `Route` both share some method names in common (where the `Router` just calls `r.NewRoute().<Method>(...)` I _think_ that many of the examples are actually syntactically correct. However, the _intent_ may have been to demonstrate something a `Route` can do specifically. I have updated all the instances where this occurred and have opened a PR for this [here](https://github.com/gorilla/mux/pull/672)

**Comment by Algebra8** [comment]
Sorry for the delay, I got busy with some other things and lost track of this issue 😞 

@andrew-werdna thanks for bringing that point up, and it's a great point, but in my opinion the documentation should reflect the outer most visibility to the user and it's not great ux for the user to have to dig into the source code to come to the same realization you did.

And thanks for the PR!

**Comment by andrew-werdna** [comment]
I think I know what you mean. I had to read the source code just now to discover that both `Router` and `Route` types shared multiple method names.

**Review by james-d-elliott — APPROVED** [review]
LGTM

**Review by miicchelle — APPROVED** [review]

**Review by jrs526 — APPROVED** [review]

**Review by amustaque97 — COMMENTED** [review]
> @andrew-werdna thanks for bringing that point up, and it's a great point, but in my opinion, the documentation should reflect the outermost visibility to the user and it's not great UX for the user to have to dig into the source code to come to the same realization you did.

~Hi @Algebra8, I had a closer look at the code I believe we shouldn't update the docs but rather add a new method  `HeadersRegexp` in the `mux.go` file like it is done for other multiple methods.~

UPDATE: I'm okay with the current changes.

**Review by coreydaley — APPROVED** [review]

**Comment by coreydaley** [comment]
@apoorvajagtap ptal

**Comment by apoorvajagtap** [comment]
@coreydaley I think we can close this one, as #672 incorporates' HeadersRegexp'. Let me know in case I missed anything.

**Pull request closed without merging**
