### PR TITLE
Feature route middleware with `.Use`

### PR DESCRIPTION
**Pull request by cornejong**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Go Version Update
- [ ] Dependency Update

## Description
Added support for route specific middleware using the `.Use` method.
Using the `.Use` method on `Route` middlewares can be set on a specific route.

Example:
```go
router.HandleFunc("/", handlerFunc).Use(middleware)
```

## Related Tickets & Documents

- Related Issue #
- Closes #

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why:
- [ ] I need help with writing tests

## Run verifications and test

- [x] `make verify` is passing
- [x] `make test` is passing

### CODE REVIEW

**Comment by cornejong** [comment]
Currently, you can add middleware to a single route by wrapping the handler in it:
```go
router.Handle("/", middleware(http.HandlerFunc(myHandlerFunc)))
```
This approach works fine for a single middleware but becomes cluttered quickly when adding more than one:

```go
router.Handle("/", middleware1(middleware2(http.HandlerFunc(myHandlerFunc))))
```
This got me thinking that it would be great if we could assign middleware to a route using the .Use method, similar to how it's done on the router. This would result in cleaner, more consistent, and more readable code. For example:
```go
router.HandleFunc("/", handlerFunc)
    .Methods(http.MethodGet)
    .Use(middleware1, middleware2)
    .Name("route")
```

**Comment by pcfreak30** [comment]
really appreciate creating this. I am needing this now to keep my sanity, lol.

would love to see this merged

**Comment by AlexVulaj** [comment]
This looks like a pretty solid addition, thanks for the contribution!

**Review by AlexVulaj — APPROVED** [review]

**Comment by cornejong** [comment]
Thanks for the merge! Always happy to contribute.

**Pull request merged**
