### PR TITLE
Stripe tail slash in PathPrefix

### PR DESCRIPTION
**Pull request by mrcyna**
As I was following the example and Test the API for the first time (BY THE WAY IT IS AWWWWSOME! & I LOVE IT)
I just had a problem in example and I figured out that maybe this would be misleading for other noob devs like me

Thanks so much

### CODE REVIEW

**Comment by fharding1** [comment]
Could you elaborate on how the trailing slash was misleading?

**Comment by mrcyna** [comment]
Hi

For example:
I write r.HandleFunc("/products/{key}", ProductHandler) and then add Prefix like this:
r.HandleFunc("/products/{key}", ProductHandler).PathPrefix("/foo/")

The route will be  "/foo//products/{key}" and I think double slashes somehow is misleading 

Thanks for your attention

**Comment by elithrar** [comment]
It would make more sense to update the documentation for `PathPrefix` - a trailing slash has meaning here, and omitting it from the example may cause _more_ confusion.

https://pkg.go.dev/github.com/gorilla/mux?tab=doc#Route.PathPrefix

**Comment by mrcyna** [comment]
You are right. I read the document again

Thanks for your attention

**Pull request closed without merging**
