### PR TITLE
fix: regression in vars extract for wildcard host

### PR DESCRIPTION
**Pull request by harshavardhana**
Continuing from PR #447 we have to add extra
check to ignore the port as well

### CODE REVIEW

**Comment by harshavardhana** [comment]
// cc @elithrar

**Comment by elithrar** [comment]
Can you please add regression tests that capture this change? :)

**Comment by harshavardhana** [comment]
@elithrar let me look at those - thanks for quickly looking at the PR.

**Comment by harshavardhana** [comment]
would it be possible to make a release today if all goes well? @elithrar

**Comment by elithrar** [comment]
I'll commit to having this reviewed before the end of the weekend.

**Comment by harshavardhana** [comment]
@elithrar updated the PR with the tests, the same tests don't run with master branch.

**Comment by harshavardhana** [comment]
Possible to tag a release @elithrar ?

**Comment by harshavardhana** [comment]
> Possible to tag a release @elithrar ?

checking back to see if there can be a tagged release? @elithrar

**Pull request merged**
