### PR TITLE
Basic authorization matcher.

### PR DESCRIPTION
**Pull request by alesstimec**
BasicAuthorization enables one to secure routes using basic username&password-based authorization.

### CODE REVIEW

**Comment by tasdomas** [comment]
This looks like a valuable improvement.

**Comment by kisielk** [comment]
Curious as to what the use-case for this is? I can't think of a situation where I'd define a route that only matches one particular username and password. Usually I would wrap the router or a path prefix in another handler that does authentication.

**Comment by alesstimec** [comment]
@kisielk use-case is when you want to secure only a specific endpoint using basic auth, and when you're using subrouters.. example:
root := mux.NewRouter()
secureSubrouter := root.PathPrefix("secure").BasicAuthorization("username", "password").Subrouter()
publicSubrouter := root.PathPrefix("public").SubRouter()

now i can register handlers to each subrouter and have them either secure or public..

**Comment by avrtno** [comment]
Should the server reply with the www authenticate challenge for unauthorized access?  If yes, then this feature does not belong in the router.  If no, what is the use case for this feature?

What are some use cases where the application authenticates against exactly one user name and password where the password is static for the lifetime of the application process? 

Should other authentication methods be supported in the router?  If no, then what's so special about basic auth that it's added?

Use the standard library to parse and format the auth headers:

    func (m *authorizationMatcher) Match(req *http.Request, match *RouteMatch) bool {
        u, p, ok := req.BasicAuth()
        return ok && u == m.username && p = m.pasword
    }

    func newRequestWithCredentials(method, url, username, password string) *http.Request {
	req, err := http.NewRequest(method, url, nil)
	if err != nil {
		panic(err)
	}
        req.SetBasicAuth(username, password)
        return req
    }

**Comment by kisielk** [comment]
I agree with @avrtno, I've never seen a scenario where you'd want to authorize exactly one hardcoded user in a real application. There is usually a lot more complex machinery involved which is beyond the scope of this package.

**Pull request closed without merging**
