### PR TITLE
HTTPS Routes Building

### PR DESCRIPTION
**Pull request by adone**
Proposal for #13

### CODE REVIEW

**Comment by elithrar** [comment]
Looks good: can you add a test for this as well? @ADone

**Comment by odlp** [comment]
Hi @ADone - can I offer any assistance on this PR to add the test requested so it can be merged to master?

Would love to use this feature via gorilla/mux rather than the fork so we can stay current.

**Comment by ADone** [comment]
Hi @odlp! It will be great! I don't have enough free time for this 😞

**Comment by odlp** [comment]
@ADone I had a shot at this but got stuck trying to introduce a new `route_test.go` file and was unsure whether to layer the tests into `mux_test.go`. Any hints on the best level to test this at?

**Comment by kisielk** [comment]
@odlp What kind of problems were you having with adding tests?

**Comment by kisielk** [comment]
Ping @odlp . Is there still interest in merging this?

**Comment by odlp** [comment]
Sorry I switched teams and don't work on a project using Gorilla Mux any longer, so I don't think I'll get round to this. Apologies for not updating the PR.

**Comment by ChrisHines** [comment]
I am interested in moving this PR forward. I can work on adding tests.

**Comment by adone** [comment]
added test for https URL building
not sure it is enough

**Comment by ChrisHines** [comment]
What was the thinking behind the implementation in this PR? In particular, why does `Route.URL` only choose a scheme of "http" or "https", and why is "https" always take priority when multiple schemes are configured?

Was the idea proposed by @kisielk in https://github.com/gorilla/mux/issues/13#issuecomment-13209910 rejected or found to be a bad idea for some reason?

**Comment by kisielk** [comment]
I agree with @ChrisHines . The `isSecure()` method seems a bit weird to me in comparison to actually checking for the `schemesMatcher` and returning the first found scheme.

**Comment by adone** [comment]
I am not interesting in upgrade this PR for more complex logic because I don't use mux anymore

**Comment by elithrar** [comment]
Marking as helpwanted.

**Comment by ChrisHines** [comment]
I will take this over. I plan to change the implementation to use the first registered scheme or a default of "http" when no schemes are registered. I will open a new PR when I have it ready.

**Comment by elithrar** [comment]
Thanks @ChrisHines - appreciated!

**Comment by kisielk** [comment]
@ChrisHines @elithrar can this be closed now?

**Comment by ChrisHines** [comment]
@kisielk Yes. #260 and #280 make this PR obsolete.

**Pull request closed without merging**
